[build]
  command = "npm run build"

[build.environment]
  NODE_VERSION = "22"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@supabase/supabase-js","@supabase/ssr"]

[[plugins]]
  package = "@netlify/plugin-nextjs"