/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file should not be edited
// It is automatically generated by Next.js
// and will be overwritten when you run `next dev` or `next build`